spring:
  application:
    name: cpmt-singleton

  rabbitmq:
    addresses: ${rabbitmq.address}
    port: ${rabbitmq.port}
    username: ${rabbitmq.user}
    password: ${rabbitmq.password}

  redis:
    database: ${redis.database.singleton}
    host: ${redis.host} #read from config-server
    port: ${redis.port}
    password: ${redis.password}
    timeout: ${redis.timeout}
    pool:
      max-active: 20
      max-wait: 2000
      max-idle: 10
  datasource:
    driver-class-name: ${ds.driver}
    url: ${ds.url}
    username: ${ds.username}
    password: ${ds.password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 25
      connection-timeout: 10000
      connection-test-query: SELECT 1
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non-null
    deserialization:
      fail-on-unknown-properties: false

    
    
mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 28040

management:
  port: 29040  
  security:
    enabled: false
  context-path: /mgmt
  

logging:
  level:
    root: WARN
    com.cpit.cpmt: ${log.cpmt.level}
  file: ${spring.application.name}.log   