eureka:
  instance:
    prefer-ip-address: true
    
spring:  
  cloud:
    loadbalancer:
      retry:
        enabled: false
        
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false      